//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TypeBindingSample {
    using System;
    using System.Collections.Generic;
    using System.Text;
    using System.Reflection;
    using Microsoft.SpecExplorer.Runtime.Testing;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Spec Explorer", "3.5.3146.0")]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class TestSuite : VsTestClassBase {
        
        public TestSuite() {
            this.SetSwitch("ProceedControlTimeout", "100");
            this.SetSwitch("QuiescenceTimeout", "30000");
        }
        
        #region Variables
        private IVariable<TypeBindingSample.Account> o;
        #endregion
        
        #region Test Initialization and Cleanup
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize() {
            this.InitializeTestManager();
            this.o = this.Manager.CreateVariable<TypeBindingSample.Account>("o");
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void TestCleanup() {
            this.CleanupTestManager();
        }
        #endregion
        
        #region Test Starting in S0
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void TestSuiteS0() {
            this.Manager.BeginTest("TestSuiteS0");
            this.Manager.Comment("reaching state \'S0\'");
            TypeBindingSample.Account temp0;
            this.Manager.Comment("executing step \'call CreateAccount()\'");
            temp0 = TypeBindingSample.AccountImpl.CreateAccount();
            this.Manager.Comment("reaching state \'S1\'");
            this.Manager.Comment("checking step \'return CreateAccount/AccountDefinition#0\'");
            TestManagerHelpers.AssertBind<TypeBindingSample.Account>(this.Manager, this.o, temp0, "return of CreateAccount, state S1");
            this.Manager.Comment("reaching state \'S14\'");
            float temp1;
            this.Manager.Comment("executing step \'call GetBalance(AccountDefinition#0)\'");
            temp1 = TypeBindingSample.AccountImpl.GetBalance(this.o.Value);
            this.Manager.Comment("reaching state \'S21\'");
            this.Manager.Comment("checking step \'return GetBalance/0F\'");
            TestManagerHelpers.AssertAreEqual<float>(this.Manager, ((float)(0D)), temp1, "return of GetBalance, state S21");
            this.Manager.Comment("reaching state \'S28\'");
            Microsoft.Modeling.Set<TypeBindingSample.Account> temp2;
            this.Manager.Comment("executing step \'call SearchAccounts(100F)\'");
            temp2 = TypeBindingSample.AccountImpl.SearchAccounts(((float)(100D)));
            this.Manager.Comment("reaching state \'S35\'");
            this.Manager.Comment("checking step \'return SearchAccounts/{}\'");
            TestManagerHelpers.AssertNotNull(this.Manager, temp2, "return of SearchAccounts, state S35");
            TestManagerHelpers.AssertAreEqual<Microsoft.Xrt.Runtime.RuntimeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>>(this.Manager, Microsoft.Xrt.Runtime.RuntimeSupport.MakeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>(), temp2.Rep, "return of SearchAccounts, state S35, field selection Rep");
            this.Manager.Comment("reaching state \'S42\'");
            Microsoft.Modeling.Set<TypeBindingSample.Account> temp3;
            this.Manager.Comment("executing step \'call SearchAccounts(20F)\'");
            temp3 = TypeBindingSample.AccountImpl.SearchAccounts(((float)(20D)));
            this.Manager.Comment("reaching state \'S49\'");
            this.Manager.Comment("checking step \'return SearchAccounts/{}\'");
            TestManagerHelpers.AssertNotNull(this.Manager, temp3, "return of SearchAccounts, state S49");
            TestManagerHelpers.AssertAreEqual<Microsoft.Xrt.Runtime.RuntimeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>>(this.Manager, Microsoft.Xrt.Runtime.RuntimeSupport.MakeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>(), temp3.Rep, "return of SearchAccounts, state S49, field selection Rep");
            this.Manager.Comment("reaching state \'S56\'");
            this.Manager.Comment("executing step \'call SetBalance(AccountDefinition#0,10F)\'");
            TypeBindingSample.AccountImpl.SetBalance(this.o.Value, ((float)(10D)));
            this.Manager.Comment("reaching state \'S63\'");
            this.Manager.Comment("checking step \'return SetBalance\'");
            this.Manager.Comment("reaching state \'S70\'");
            float temp4;
            this.Manager.Comment("executing step \'call GetBalance(AccountDefinition#0)\'");
            temp4 = TypeBindingSample.AccountImpl.GetBalance(this.o.Value);
            this.Manager.Comment("reaching state \'S77\'");
            this.Manager.Comment("checking step \'return GetBalance/10F\'");
            TestManagerHelpers.AssertAreEqual<float>(this.Manager, ((float)(10D)), temp4, "return of GetBalance, state S77");
            this.Manager.Comment("reaching state \'S83\'");
            Microsoft.Modeling.Set<TypeBindingSample.Account> temp5;
            this.Manager.Comment("executing step \'call SearchAccounts(100F)\'");
            temp5 = TypeBindingSample.AccountImpl.SearchAccounts(((float)(100D)));
            this.Manager.Comment("reaching state \'S89\'");
            this.Manager.Comment("checking step \'return SearchAccounts/{}\'");
            TestManagerHelpers.AssertNotNull(this.Manager, temp5, "return of SearchAccounts, state S89");
            TestManagerHelpers.AssertAreEqual<Microsoft.Xrt.Runtime.RuntimeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>>(this.Manager, Microsoft.Xrt.Runtime.RuntimeSupport.MakeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>(), temp5.Rep, "return of SearchAccounts, state S89, field selection Rep");
            this.Manager.Comment("reaching state \'S95\'");
            Microsoft.Modeling.Set<TypeBindingSample.Account> temp6;
            this.Manager.Comment("executing step \'call SearchAccounts(20F)\'");
            temp6 = TypeBindingSample.AccountImpl.SearchAccounts(((float)(20D)));
            this.Manager.Comment("reaching state \'S101\'");
            this.Manager.Comment("checking step \'return SearchAccounts/{}\'");
            TestManagerHelpers.AssertNotNull(this.Manager, temp6, "return of SearchAccounts, state S101");
            TestManagerHelpers.AssertAreEqual<Microsoft.Xrt.Runtime.RuntimeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>>(this.Manager, Microsoft.Xrt.Runtime.RuntimeSupport.MakeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>(), temp6.Rep, "return of SearchAccounts, state S101, field selection Rep");
            this.Manager.Comment("reaching state \'S107\'");
            this.Manager.Comment("executing step \'call SetBalance(AccountDefinition#0,10F)\'");
            TypeBindingSample.AccountImpl.SetBalance(this.o.Value, ((float)(10D)));
            this.Manager.Comment("reaching state \'S113\'");
            this.Manager.Comment("checking step \'return SetBalance\'");
            this.Manager.Comment("reaching state \'S119\'");
            float temp7;
            this.Manager.Comment("executing step \'call GetBalance(AccountDefinition#0)\'");
            temp7 = TypeBindingSample.AccountImpl.GetBalance(this.o.Value);
            this.Manager.Comment("reaching state \'S125\'");
            this.Manager.Comment("checking step \'return GetBalance/10F\'");
            TestManagerHelpers.AssertAreEqual<float>(this.Manager, ((float)(10D)), temp7, "return of GetBalance, state S125");
            this.Manager.Comment("reaching state \'S129\'");
            Microsoft.Modeling.Set<TypeBindingSample.Account> temp8;
            this.Manager.Comment("executing step \'call SearchAccounts(100F)\'");
            temp8 = TypeBindingSample.AccountImpl.SearchAccounts(((float)(100D)));
            this.Manager.Comment("reaching state \'S133\'");
            this.Manager.Comment("checking step \'return SearchAccounts/{}\'");
            TestManagerHelpers.AssertNotNull(this.Manager, temp8, "return of SearchAccounts, state S133");
            TestManagerHelpers.AssertAreEqual<Microsoft.Xrt.Runtime.RuntimeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>>(this.Manager, Microsoft.Xrt.Runtime.RuntimeSupport.MakeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>(), temp8.Rep, "return of SearchAccounts, state S133, field selection Rep");
            this.Manager.Comment("reaching state \'S137\'");
            Microsoft.Modeling.Set<TypeBindingSample.Account> temp9;
            this.Manager.Comment("executing step \'call SearchAccounts(20F)\'");
            temp9 = TypeBindingSample.AccountImpl.SearchAccounts(((float)(20D)));
            this.Manager.Comment("reaching state \'S141\'");
            this.Manager.Comment("checking step \'return SearchAccounts/{}\'");
            TestManagerHelpers.AssertNotNull(this.Manager, temp9, "return of SearchAccounts, state S141");
            TestManagerHelpers.AssertAreEqual<Microsoft.Xrt.Runtime.RuntimeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>>(this.Manager, Microsoft.Xrt.Runtime.RuntimeSupport.MakeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>(), temp9.Rep, "return of SearchAccounts, state S141, field selection Rep");
            this.Manager.Comment("reaching state \'S145\'");
            this.Manager.Comment("executing step \'call Clear()\'");
            TypeBindingSample.AccountImpl.Clear();
            this.Manager.Comment("reaching state \'S149\'");
            this.Manager.Comment("checking step \'return Clear\'");
            this.Manager.Comment("reaching state \'S153\'");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S10
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void TestSuiteS10() {
            this.Manager.BeginTest("TestSuiteS10");
            this.Manager.Comment("reaching state \'S10\'");
            TypeBindingSample.Account temp10;
            this.Manager.Comment("executing step \'call CreateAccount()\'");
            temp10 = TypeBindingSample.AccountImpl.CreateAccount();
            this.Manager.Comment("reaching state \'S11\'");
            this.Manager.Comment("checking step \'return CreateAccount/AccountDefinition#0\'");
            TestManagerHelpers.AssertBind<TypeBindingSample.Account>(this.Manager, this.o, temp10, "return of CreateAccount, state S11");
            this.Manager.Comment("reaching state \'S19\'");
            float temp11;
            this.Manager.Comment("executing step \'call GetBalance(AccountDefinition#0)\'");
            temp11 = TypeBindingSample.AccountImpl.GetBalance(this.o.Value);
            this.Manager.Comment("reaching state \'S26\'");
            this.Manager.Comment("checking step \'return GetBalance/0F\'");
            TestManagerHelpers.AssertAreEqual<float>(this.Manager, ((float)(0D)), temp11, "return of GetBalance, state S26");
            this.Manager.Comment("reaching state \'S33\'");
            Microsoft.Modeling.Set<TypeBindingSample.Account> temp12;
            this.Manager.Comment("executing step \'call SearchAccounts(100F)\'");
            temp12 = TypeBindingSample.AccountImpl.SearchAccounts(((float)(100D)));
            this.Manager.Comment("reaching state \'S40\'");
            this.Manager.Comment("checking step \'return SearchAccounts/{}\'");
            TestManagerHelpers.AssertNotNull(this.Manager, temp12, "return of SearchAccounts, state S40");
            TestManagerHelpers.AssertAreEqual<Microsoft.Xrt.Runtime.RuntimeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>>(this.Manager, Microsoft.Xrt.Runtime.RuntimeSupport.MakeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>(), temp12.Rep, "return of SearchAccounts, state S40, field selection Rep");
            this.Manager.Comment("reaching state \'S47\'");
            Microsoft.Modeling.Set<TypeBindingSample.Account> temp13;
            this.Manager.Comment("executing step \'call SearchAccounts(20F)\'");
            temp13 = TypeBindingSample.AccountImpl.SearchAccounts(((float)(20D)));
            this.Manager.Comment("reaching state \'S54\'");
            this.Manager.Comment("checking step \'return SearchAccounts/{}\'");
            TestManagerHelpers.AssertNotNull(this.Manager, temp13, "return of SearchAccounts, state S54");
            TestManagerHelpers.AssertAreEqual<Microsoft.Xrt.Runtime.RuntimeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>>(this.Manager, Microsoft.Xrt.Runtime.RuntimeSupport.MakeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>(), temp13.Rep, "return of SearchAccounts, state S54, field selection Rep");
            this.Manager.Comment("reaching state \'S61\'");
            this.Manager.Comment("executing step \'call SetBalance(AccountDefinition#0,100F)\'");
            TypeBindingSample.AccountImpl.SetBalance(this.o.Value, ((float)(100D)));
            this.Manager.Comment("reaching state \'S68\'");
            this.Manager.Comment("checking step \'return SetBalance\'");
            this.Manager.Comment("reaching state \'S75\'");
            float temp14;
            this.Manager.Comment("executing step \'call GetBalance(AccountDefinition#0)\'");
            temp14 = TypeBindingSample.AccountImpl.GetBalance(this.o.Value);
            this.Manager.Comment("reaching state \'S82\'");
            this.Manager.Comment("checking step \'return GetBalance/100F\'");
            TestManagerHelpers.AssertAreEqual<float>(this.Manager, ((float)(100D)), temp14, "return of GetBalance, state S82");
            this.Manager.Comment("reaching state \'S88\'");
            Microsoft.Modeling.Set<TypeBindingSample.Account> temp15;
            this.Manager.Comment("executing step \'call SearchAccounts(20F)\'");
            temp15 = TypeBindingSample.AccountImpl.SearchAccounts(((float)(20D)));
            this.Manager.Comment("reaching state \'S94\'");
            this.Manager.Comment("checking step \'return SearchAccounts/{}\'");
            TestManagerHelpers.AssertNotNull(this.Manager, temp15, "return of SearchAccounts, state S94");
            TestManagerHelpers.AssertAreEqual<Microsoft.Xrt.Runtime.RuntimeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>>(this.Manager, Microsoft.Xrt.Runtime.RuntimeSupport.MakeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>(), temp15.Rep, "return of SearchAccounts, state S94, field selection Rep");
            this.Manager.Comment("reaching state \'S100\'");
            Microsoft.Modeling.Set<TypeBindingSample.Account> temp16;
            this.Manager.Comment("executing step \'call SearchAccounts(100F)\'");
            temp16 = TypeBindingSample.AccountImpl.SearchAccounts(((float)(100D)));
            this.Manager.Comment("reaching state \'S106\'");
            this.Manager.Comment("checking step \'return SearchAccounts/{Account{AccountDefinition#0}}\'");
            TestManagerHelpers.AssertNotNull(this.Manager, temp16, "return of SearchAccounts, state S106");
            TestManagerHelpers.AssertAreEqual<Microsoft.Xrt.Runtime.RuntimeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>>(this.Manager, Microsoft.Xrt.Runtime.RuntimeSupport.UpdateMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>(Microsoft.Xrt.Runtime.RuntimeSupport.MakeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>(), this.o.Value, this.Make<Microsoft.Xrt.Runtime.RuntimeMapElement<Microsoft.Xrt.Runtime.Singleton>>(new string[] {
                                "Element"}, new object[] {
                                Microsoft.Xrt.Runtime.Singleton.Single})), temp16.Rep, "return of SearchAccounts, state S106, field selection Rep");
            this.Manager.Comment("reaching state \'S112\'");
            this.Manager.Comment("executing step \'call Clear()\'");
            TypeBindingSample.AccountImpl.Clear();
            this.Manager.Comment("reaching state \'S118\'");
            this.Manager.Comment("checking step \'return Clear\'");
            this.Manager.Comment("reaching state \'S124\'");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S12
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void TestSuiteS12() {
            this.Manager.BeginTest("TestSuiteS12");
            this.Manager.Comment("reaching state \'S12\'");
            TypeBindingSample.Account temp17;
            this.Manager.Comment("executing step \'call CreateAccount()\'");
            temp17 = TypeBindingSample.AccountImpl.CreateAccount();
            this.Manager.Comment("reaching state \'S13\'");
            this.Manager.Comment("checking step \'return CreateAccount/AccountDefinition#0\'");
            TestManagerHelpers.AssertBind<TypeBindingSample.Account>(this.Manager, this.o, temp17, "return of CreateAccount, state S13");
            this.Manager.Comment("reaching state \'S20\'");
            float temp18;
            this.Manager.Comment("executing step \'call GetBalance(AccountDefinition#0)\'");
            temp18 = TypeBindingSample.AccountImpl.GetBalance(this.o.Value);
            this.Manager.Comment("reaching state \'S27\'");
            this.Manager.Comment("checking step \'return GetBalance/0F\'");
            TestManagerHelpers.AssertAreEqual<float>(this.Manager, ((float)(0D)), temp18, "return of GetBalance, state S27");
            this.Manager.Comment("reaching state \'S34\'");
            Microsoft.Modeling.Set<TypeBindingSample.Account> temp19;
            this.Manager.Comment("executing step \'call SearchAccounts(100F)\'");
            temp19 = TypeBindingSample.AccountImpl.SearchAccounts(((float)(100D)));
            this.Manager.Comment("reaching state \'S41\'");
            this.Manager.Comment("checking step \'return SearchAccounts/{}\'");
            TestManagerHelpers.AssertNotNull(this.Manager, temp19, "return of SearchAccounts, state S41");
            TestManagerHelpers.AssertAreEqual<Microsoft.Xrt.Runtime.RuntimeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>>(this.Manager, Microsoft.Xrt.Runtime.RuntimeSupport.MakeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>(), temp19.Rep, "return of SearchAccounts, state S41, field selection Rep");
            this.Manager.Comment("reaching state \'S48\'");
            Microsoft.Modeling.Set<TypeBindingSample.Account> temp20;
            this.Manager.Comment("executing step \'call SearchAccounts(20F)\'");
            temp20 = TypeBindingSample.AccountImpl.SearchAccounts(((float)(20D)));
            this.Manager.Comment("reaching state \'S55\'");
            this.Manager.Comment("checking step \'return SearchAccounts/{}\'");
            TestManagerHelpers.AssertNotNull(this.Manager, temp20, "return of SearchAccounts, state S55");
            TestManagerHelpers.AssertAreEqual<Microsoft.Xrt.Runtime.RuntimeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>>(this.Manager, Microsoft.Xrt.Runtime.RuntimeSupport.MakeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>(), temp20.Rep, "return of SearchAccounts, state S55, field selection Rep");
            this.Manager.Comment("reaching state \'S62\'");
            this.Manager.Comment("executing step \'call Clear()\'");
            TypeBindingSample.AccountImpl.Clear();
            this.Manager.Comment("reaching state \'S69\'");
            this.Manager.Comment("checking step \'return Clear\'");
            this.Manager.Comment("reaching state \'S76\'");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S2
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void TestSuiteS2() {
            this.Manager.BeginTest("TestSuiteS2");
            this.Manager.Comment("reaching state \'S2\'");
            TypeBindingSample.Account temp21;
            this.Manager.Comment("executing step \'call CreateAccount()\'");
            temp21 = TypeBindingSample.AccountImpl.CreateAccount();
            this.Manager.Comment("reaching state \'S3\'");
            this.Manager.Comment("checking step \'return CreateAccount/AccountDefinition#0\'");
            TestManagerHelpers.AssertBind<TypeBindingSample.Account>(this.Manager, this.o, temp21, "return of CreateAccount, state S3");
            this.Manager.Comment("reaching state \'S15\'");
            float temp22;
            this.Manager.Comment("executing step \'call GetBalance(AccountDefinition#0)\'");
            temp22 = TypeBindingSample.AccountImpl.GetBalance(this.o.Value);
            this.Manager.Comment("reaching state \'S22\'");
            this.Manager.Comment("checking step \'return GetBalance/0F\'");
            TestManagerHelpers.AssertAreEqual<float>(this.Manager, ((float)(0D)), temp22, "return of GetBalance, state S22");
            this.Manager.Comment("reaching state \'S29\'");
            Microsoft.Modeling.Set<TypeBindingSample.Account> temp23;
            this.Manager.Comment("executing step \'call SearchAccounts(100F)\'");
            temp23 = TypeBindingSample.AccountImpl.SearchAccounts(((float)(100D)));
            this.Manager.Comment("reaching state \'S36\'");
            this.Manager.Comment("checking step \'return SearchAccounts/{}\'");
            TestManagerHelpers.AssertNotNull(this.Manager, temp23, "return of SearchAccounts, state S36");
            TestManagerHelpers.AssertAreEqual<Microsoft.Xrt.Runtime.RuntimeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>>(this.Manager, Microsoft.Xrt.Runtime.RuntimeSupport.MakeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>(), temp23.Rep, "return of SearchAccounts, state S36, field selection Rep");
            this.Manager.Comment("reaching state \'S43\'");
            Microsoft.Modeling.Set<TypeBindingSample.Account> temp24;
            this.Manager.Comment("executing step \'call SearchAccounts(20F)\'");
            temp24 = TypeBindingSample.AccountImpl.SearchAccounts(((float)(20D)));
            this.Manager.Comment("reaching state \'S50\'");
            this.Manager.Comment("checking step \'return SearchAccounts/{}\'");
            TestManagerHelpers.AssertNotNull(this.Manager, temp24, "return of SearchAccounts, state S50");
            TestManagerHelpers.AssertAreEqual<Microsoft.Xrt.Runtime.RuntimeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>>(this.Manager, Microsoft.Xrt.Runtime.RuntimeSupport.MakeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>(), temp24.Rep, "return of SearchAccounts, state S50, field selection Rep");
            this.Manager.Comment("reaching state \'S57\'");
            this.Manager.Comment("executing step \'call SetBalance(AccountDefinition#0,10F)\'");
            TypeBindingSample.AccountImpl.SetBalance(this.o.Value, ((float)(10D)));
            this.Manager.Comment("reaching state \'S64\'");
            this.Manager.Comment("checking step \'return SetBalance\'");
            this.Manager.Comment("reaching state \'S71\'");
            float temp25;
            this.Manager.Comment("executing step \'call GetBalance(AccountDefinition#0)\'");
            temp25 = TypeBindingSample.AccountImpl.GetBalance(this.o.Value);
            this.Manager.Comment("reaching state \'S78\'");
            this.Manager.Comment("checking step \'return GetBalance/10F\'");
            TestManagerHelpers.AssertAreEqual<float>(this.Manager, ((float)(10D)), temp25, "return of GetBalance, state S78");
            this.Manager.Comment("reaching state \'S84\'");
            Microsoft.Modeling.Set<TypeBindingSample.Account> temp26;
            this.Manager.Comment("executing step \'call SearchAccounts(100F)\'");
            temp26 = TypeBindingSample.AccountImpl.SearchAccounts(((float)(100D)));
            this.Manager.Comment("reaching state \'S90\'");
            this.Manager.Comment("checking step \'return SearchAccounts/{}\'");
            TestManagerHelpers.AssertNotNull(this.Manager, temp26, "return of SearchAccounts, state S90");
            TestManagerHelpers.AssertAreEqual<Microsoft.Xrt.Runtime.RuntimeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>>(this.Manager, Microsoft.Xrt.Runtime.RuntimeSupport.MakeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>(), temp26.Rep, "return of SearchAccounts, state S90, field selection Rep");
            this.Manager.Comment("reaching state \'S96\'");
            Microsoft.Modeling.Set<TypeBindingSample.Account> temp27;
            this.Manager.Comment("executing step \'call SearchAccounts(20F)\'");
            temp27 = TypeBindingSample.AccountImpl.SearchAccounts(((float)(20D)));
            this.Manager.Comment("reaching state \'S102\'");
            this.Manager.Comment("checking step \'return SearchAccounts/{}\'");
            TestManagerHelpers.AssertNotNull(this.Manager, temp27, "return of SearchAccounts, state S102");
            TestManagerHelpers.AssertAreEqual<Microsoft.Xrt.Runtime.RuntimeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>>(this.Manager, Microsoft.Xrt.Runtime.RuntimeSupport.MakeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>(), temp27.Rep, "return of SearchAccounts, state S102, field selection Rep");
            this.Manager.Comment("reaching state \'S108\'");
            this.Manager.Comment("executing step \'call SetBalance(AccountDefinition#0,100F)\'");
            TypeBindingSample.AccountImpl.SetBalance(this.o.Value, ((float)(100D)));
            this.Manager.Comment("reaching state \'S114\'");
            this.Manager.Comment("checking step \'return SetBalance\'");
            this.Manager.Comment("reaching state \'S120\'");
            float temp28;
            this.Manager.Comment("executing step \'call GetBalance(AccountDefinition#0)\'");
            temp28 = TypeBindingSample.AccountImpl.GetBalance(this.o.Value);
            this.Manager.Comment("reaching state \'S126\'");
            this.Manager.Comment("checking step \'return GetBalance/100F\'");
            TestManagerHelpers.AssertAreEqual<float>(this.Manager, ((float)(100D)), temp28, "return of GetBalance, state S126");
            this.Manager.Comment("reaching state \'S130\'");
            Microsoft.Modeling.Set<TypeBindingSample.Account> temp29;
            this.Manager.Comment("executing step \'call SearchAccounts(20F)\'");
            temp29 = TypeBindingSample.AccountImpl.SearchAccounts(((float)(20D)));
            this.Manager.Comment("reaching state \'S134\'");
            this.Manager.Comment("checking step \'return SearchAccounts/{}\'");
            TestManagerHelpers.AssertNotNull(this.Manager, temp29, "return of SearchAccounts, state S134");
            TestManagerHelpers.AssertAreEqual<Microsoft.Xrt.Runtime.RuntimeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>>(this.Manager, Microsoft.Xrt.Runtime.RuntimeSupport.MakeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>(), temp29.Rep, "return of SearchAccounts, state S134, field selection Rep");
            this.Manager.Comment("reaching state \'S138\'");
            Microsoft.Modeling.Set<TypeBindingSample.Account> temp30;
            this.Manager.Comment("executing step \'call SearchAccounts(100F)\'");
            temp30 = TypeBindingSample.AccountImpl.SearchAccounts(((float)(100D)));
            this.Manager.Comment("reaching state \'S142\'");
            this.Manager.Comment("checking step \'return SearchAccounts/{Account{AccountDefinition#0}}\'");
            TestManagerHelpers.AssertNotNull(this.Manager, temp30, "return of SearchAccounts, state S142");
            TestManagerHelpers.AssertAreEqual<Microsoft.Xrt.Runtime.RuntimeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>>(this.Manager, Microsoft.Xrt.Runtime.RuntimeSupport.UpdateMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>(Microsoft.Xrt.Runtime.RuntimeSupport.MakeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>(), this.o.Value, this.Make<Microsoft.Xrt.Runtime.RuntimeMapElement<Microsoft.Xrt.Runtime.Singleton>>(new string[] {
                                "Element"}, new object[] {
                                Microsoft.Xrt.Runtime.Singleton.Single})), temp30.Rep, "return of SearchAccounts, state S142, field selection Rep");
            this.Manager.Comment("reaching state \'S146\'");
            this.Manager.Comment("executing step \'call SetBalance(AccountDefinition#0,10F)\'");
            TypeBindingSample.AccountImpl.SetBalance(this.o.Value, ((float)(10D)));
            this.Manager.Comment("reaching state \'S150\'");
            this.Manager.Comment("checking step \'return SetBalance\'");
            this.Manager.Comment("reaching state \'S154\'");
            float temp31;
            this.Manager.Comment("executing step \'call GetBalance(AccountDefinition#0)\'");
            temp31 = TypeBindingSample.AccountImpl.GetBalance(this.o.Value);
            this.Manager.Comment("reaching state \'S157\'");
            this.Manager.Comment("checking step \'return GetBalance/10F\'");
            TestManagerHelpers.AssertAreEqual<float>(this.Manager, ((float)(10D)), temp31, "return of GetBalance, state S157");
            this.Manager.Comment("reaching state \'S159\'");
            Microsoft.Modeling.Set<TypeBindingSample.Account> temp32;
            this.Manager.Comment("executing step \'call SearchAccounts(100F)\'");
            temp32 = TypeBindingSample.AccountImpl.SearchAccounts(((float)(100D)));
            this.Manager.Comment("reaching state \'S161\'");
            this.Manager.Comment("checking step \'return SearchAccounts/{}\'");
            TestManagerHelpers.AssertNotNull(this.Manager, temp32, "return of SearchAccounts, state S161");
            TestManagerHelpers.AssertAreEqual<Microsoft.Xrt.Runtime.RuntimeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>>(this.Manager, Microsoft.Xrt.Runtime.RuntimeSupport.MakeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>(), temp32.Rep, "return of SearchAccounts, state S161, field selection Rep");
            this.Manager.Comment("reaching state \'S163\'");
            Microsoft.Modeling.Set<TypeBindingSample.Account> temp33;
            this.Manager.Comment("executing step \'call SearchAccounts(20F)\'");
            temp33 = TypeBindingSample.AccountImpl.SearchAccounts(((float)(20D)));
            this.Manager.Comment("reaching state \'S165\'");
            this.Manager.Comment("checking step \'return SearchAccounts/{}\'");
            TestManagerHelpers.AssertNotNull(this.Manager, temp33, "return of SearchAccounts, state S165");
            TestManagerHelpers.AssertAreEqual<Microsoft.Xrt.Runtime.RuntimeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>>(this.Manager, Microsoft.Xrt.Runtime.RuntimeSupport.MakeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>(), temp33.Rep, "return of SearchAccounts, state S165, field selection Rep");
            this.Manager.Comment("reaching state \'S167\'");
            this.Manager.Comment("executing step \'call Clear()\'");
            TypeBindingSample.AccountImpl.Clear();
            this.Manager.Comment("reaching state \'S169\'");
            this.Manager.Comment("checking step \'return Clear\'");
            this.Manager.Comment("reaching state \'S171\'");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S4
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void TestSuiteS4() {
            this.Manager.BeginTest("TestSuiteS4");
            this.Manager.Comment("reaching state \'S4\'");
            TypeBindingSample.Account temp34;
            this.Manager.Comment("executing step \'call CreateAccount()\'");
            temp34 = TypeBindingSample.AccountImpl.CreateAccount();
            this.Manager.Comment("reaching state \'S5\'");
            this.Manager.Comment("checking step \'return CreateAccount/AccountDefinition#0\'");
            TestManagerHelpers.AssertBind<TypeBindingSample.Account>(this.Manager, this.o, temp34, "return of CreateAccount, state S5");
            this.Manager.Comment("reaching state \'S16\'");
            float temp35;
            this.Manager.Comment("executing step \'call GetBalance(AccountDefinition#0)\'");
            temp35 = TypeBindingSample.AccountImpl.GetBalance(this.o.Value);
            this.Manager.Comment("reaching state \'S23\'");
            this.Manager.Comment("checking step \'return GetBalance/0F\'");
            TestManagerHelpers.AssertAreEqual<float>(this.Manager, ((float)(0D)), temp35, "return of GetBalance, state S23");
            this.Manager.Comment("reaching state \'S30\'");
            Microsoft.Modeling.Set<TypeBindingSample.Account> temp36;
            this.Manager.Comment("executing step \'call SearchAccounts(100F)\'");
            temp36 = TypeBindingSample.AccountImpl.SearchAccounts(((float)(100D)));
            this.Manager.Comment("reaching state \'S37\'");
            this.Manager.Comment("checking step \'return SearchAccounts/{}\'");
            TestManagerHelpers.AssertNotNull(this.Manager, temp36, "return of SearchAccounts, state S37");
            TestManagerHelpers.AssertAreEqual<Microsoft.Xrt.Runtime.RuntimeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>>(this.Manager, Microsoft.Xrt.Runtime.RuntimeSupport.MakeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>(), temp36.Rep, "return of SearchAccounts, state S37, field selection Rep");
            this.Manager.Comment("reaching state \'S44\'");
            Microsoft.Modeling.Set<TypeBindingSample.Account> temp37;
            this.Manager.Comment("executing step \'call SearchAccounts(20F)\'");
            temp37 = TypeBindingSample.AccountImpl.SearchAccounts(((float)(20D)));
            this.Manager.Comment("reaching state \'S51\'");
            this.Manager.Comment("checking step \'return SearchAccounts/{}\'");
            TestManagerHelpers.AssertNotNull(this.Manager, temp37, "return of SearchAccounts, state S51");
            TestManagerHelpers.AssertAreEqual<Microsoft.Xrt.Runtime.RuntimeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>>(this.Manager, Microsoft.Xrt.Runtime.RuntimeSupport.MakeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>(), temp37.Rep, "return of SearchAccounts, state S51, field selection Rep");
            this.Manager.Comment("reaching state \'S58\'");
            this.Manager.Comment("executing step \'call SetBalance(AccountDefinition#0,10F)\'");
            TypeBindingSample.AccountImpl.SetBalance(this.o.Value, ((float)(10D)));
            this.Manager.Comment("reaching state \'S65\'");
            this.Manager.Comment("checking step \'return SetBalance\'");
            this.Manager.Comment("reaching state \'S72\'");
            float temp38;
            this.Manager.Comment("executing step \'call GetBalance(AccountDefinition#0)\'");
            temp38 = TypeBindingSample.AccountImpl.GetBalance(this.o.Value);
            this.Manager.Comment("reaching state \'S79\'");
            this.Manager.Comment("checking step \'return GetBalance/10F\'");
            TestManagerHelpers.AssertAreEqual<float>(this.Manager, ((float)(10D)), temp38, "return of GetBalance, state S79");
            this.Manager.Comment("reaching state \'S85\'");
            Microsoft.Modeling.Set<TypeBindingSample.Account> temp39;
            this.Manager.Comment("executing step \'call SearchAccounts(100F)\'");
            temp39 = TypeBindingSample.AccountImpl.SearchAccounts(((float)(100D)));
            this.Manager.Comment("reaching state \'S91\'");
            this.Manager.Comment("checking step \'return SearchAccounts/{}\'");
            TestManagerHelpers.AssertNotNull(this.Manager, temp39, "return of SearchAccounts, state S91");
            TestManagerHelpers.AssertAreEqual<Microsoft.Xrt.Runtime.RuntimeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>>(this.Manager, Microsoft.Xrt.Runtime.RuntimeSupport.MakeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>(), temp39.Rep, "return of SearchAccounts, state S91, field selection Rep");
            this.Manager.Comment("reaching state \'S97\'");
            Microsoft.Modeling.Set<TypeBindingSample.Account> temp40;
            this.Manager.Comment("executing step \'call SearchAccounts(20F)\'");
            temp40 = TypeBindingSample.AccountImpl.SearchAccounts(((float)(20D)));
            this.Manager.Comment("reaching state \'S103\'");
            this.Manager.Comment("checking step \'return SearchAccounts/{}\'");
            TestManagerHelpers.AssertNotNull(this.Manager, temp40, "return of SearchAccounts, state S103");
            TestManagerHelpers.AssertAreEqual<Microsoft.Xrt.Runtime.RuntimeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>>(this.Manager, Microsoft.Xrt.Runtime.RuntimeSupport.MakeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>(), temp40.Rep, "return of SearchAccounts, state S103, field selection Rep");
            this.Manager.Comment("reaching state \'S109\'");
            this.Manager.Comment("executing step \'call SetBalance(AccountDefinition#0,100F)\'");
            TypeBindingSample.AccountImpl.SetBalance(this.o.Value, ((float)(100D)));
            this.Manager.Comment("reaching state \'S115\'");
            this.Manager.Comment("checking step \'return SetBalance\'");
            this.Manager.Comment("reaching state \'S121\'");
            float temp41;
            this.Manager.Comment("executing step \'call GetBalance(AccountDefinition#0)\'");
            temp41 = TypeBindingSample.AccountImpl.GetBalance(this.o.Value);
            this.Manager.Comment("reaching state \'S127\'");
            this.Manager.Comment("checking step \'return GetBalance/100F\'");
            TestManagerHelpers.AssertAreEqual<float>(this.Manager, ((float)(100D)), temp41, "return of GetBalance, state S127");
            this.Manager.Comment("reaching state \'S131\'");
            Microsoft.Modeling.Set<TypeBindingSample.Account> temp42;
            this.Manager.Comment("executing step \'call SearchAccounts(20F)\'");
            temp42 = TypeBindingSample.AccountImpl.SearchAccounts(((float)(20D)));
            this.Manager.Comment("reaching state \'S135\'");
            this.Manager.Comment("checking step \'return SearchAccounts/{}\'");
            TestManagerHelpers.AssertNotNull(this.Manager, temp42, "return of SearchAccounts, state S135");
            TestManagerHelpers.AssertAreEqual<Microsoft.Xrt.Runtime.RuntimeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>>(this.Manager, Microsoft.Xrt.Runtime.RuntimeSupport.MakeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>(), temp42.Rep, "return of SearchAccounts, state S135, field selection Rep");
            this.Manager.Comment("reaching state \'S139\'");
            Microsoft.Modeling.Set<TypeBindingSample.Account> temp43;
            this.Manager.Comment("executing step \'call SearchAccounts(100F)\'");
            temp43 = TypeBindingSample.AccountImpl.SearchAccounts(((float)(100D)));
            this.Manager.Comment("reaching state \'S143\'");
            this.Manager.Comment("checking step \'return SearchAccounts/{Account{AccountDefinition#0}}\'");
            TestManagerHelpers.AssertNotNull(this.Manager, temp43, "return of SearchAccounts, state S143");
            TestManagerHelpers.AssertAreEqual<Microsoft.Xrt.Runtime.RuntimeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>>(this.Manager, Microsoft.Xrt.Runtime.RuntimeSupport.UpdateMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>(Microsoft.Xrt.Runtime.RuntimeSupport.MakeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>(), this.o.Value, this.Make<Microsoft.Xrt.Runtime.RuntimeMapElement<Microsoft.Xrt.Runtime.Singleton>>(new string[] {
                                "Element"}, new object[] {
                                Microsoft.Xrt.Runtime.Singleton.Single})), temp43.Rep, "return of SearchAccounts, state S143, field selection Rep");
            this.Manager.Comment("reaching state \'S147\'");
            this.Manager.Comment("executing step \'call SetBalance(AccountDefinition#0,100F)\'");
            TypeBindingSample.AccountImpl.SetBalance(this.o.Value, ((float)(100D)));
            this.Manager.Comment("reaching state \'S151\'");
            this.Manager.Comment("checking step \'return SetBalance\'");
            this.Manager.Comment("reaching state \'S155\'");
            float temp44;
            this.Manager.Comment("executing step \'call GetBalance(AccountDefinition#0)\'");
            temp44 = TypeBindingSample.AccountImpl.GetBalance(this.o.Value);
            this.Manager.Comment("reaching state \'S158\'");
            this.Manager.Comment("checking step \'return GetBalance/100F\'");
            TestManagerHelpers.AssertAreEqual<float>(this.Manager, ((float)(100D)), temp44, "return of GetBalance, state S158");
            this.Manager.Comment("reaching state \'S160\'");
            Microsoft.Modeling.Set<TypeBindingSample.Account> temp45;
            this.Manager.Comment("executing step \'call SearchAccounts(20F)\'");
            temp45 = TypeBindingSample.AccountImpl.SearchAccounts(((float)(20D)));
            this.Manager.Comment("reaching state \'S162\'");
            this.Manager.Comment("checking step \'return SearchAccounts/{}\'");
            TestManagerHelpers.AssertNotNull(this.Manager, temp45, "return of SearchAccounts, state S162");
            TestManagerHelpers.AssertAreEqual<Microsoft.Xrt.Runtime.RuntimeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>>(this.Manager, Microsoft.Xrt.Runtime.RuntimeSupport.MakeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>(), temp45.Rep, "return of SearchAccounts, state S162, field selection Rep");
            this.Manager.Comment("reaching state \'S164\'");
            Microsoft.Modeling.Set<TypeBindingSample.Account> temp46;
            this.Manager.Comment("executing step \'call SearchAccounts(100F)\'");
            temp46 = TypeBindingSample.AccountImpl.SearchAccounts(((float)(100D)));
            this.Manager.Comment("reaching state \'S166\'");
            this.Manager.Comment("checking step \'return SearchAccounts/{Account{AccountDefinition#0}}\'");
            TestManagerHelpers.AssertNotNull(this.Manager, temp46, "return of SearchAccounts, state S166");
            TestManagerHelpers.AssertAreEqual<Microsoft.Xrt.Runtime.RuntimeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>>(this.Manager, Microsoft.Xrt.Runtime.RuntimeSupport.UpdateMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>(Microsoft.Xrt.Runtime.RuntimeSupport.MakeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>(), this.o.Value, this.Make<Microsoft.Xrt.Runtime.RuntimeMapElement<Microsoft.Xrt.Runtime.Singleton>>(new string[] {
                                "Element"}, new object[] {
                                Microsoft.Xrt.Runtime.Singleton.Single})), temp46.Rep, "return of SearchAccounts, state S166, field selection Rep");
            this.Manager.Comment("reaching state \'S168\'");
            this.Manager.Comment("executing step \'call Clear()\'");
            TypeBindingSample.AccountImpl.Clear();
            this.Manager.Comment("reaching state \'S170\'");
            this.Manager.Comment("checking step \'return Clear\'");
            this.Manager.Comment("reaching state \'S172\'");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S6
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void TestSuiteS6() {
            this.Manager.BeginTest("TestSuiteS6");
            this.Manager.Comment("reaching state \'S6\'");
            TypeBindingSample.Account temp47;
            this.Manager.Comment("executing step \'call CreateAccount()\'");
            temp47 = TypeBindingSample.AccountImpl.CreateAccount();
            this.Manager.Comment("reaching state \'S7\'");
            this.Manager.Comment("checking step \'return CreateAccount/AccountDefinition#0\'");
            TestManagerHelpers.AssertBind<TypeBindingSample.Account>(this.Manager, this.o, temp47, "return of CreateAccount, state S7");
            this.Manager.Comment("reaching state \'S17\'");
            float temp48;
            this.Manager.Comment("executing step \'call GetBalance(AccountDefinition#0)\'");
            temp48 = TypeBindingSample.AccountImpl.GetBalance(this.o.Value);
            this.Manager.Comment("reaching state \'S24\'");
            this.Manager.Comment("checking step \'return GetBalance/0F\'");
            TestManagerHelpers.AssertAreEqual<float>(this.Manager, ((float)(0D)), temp48, "return of GetBalance, state S24");
            this.Manager.Comment("reaching state \'S31\'");
            Microsoft.Modeling.Set<TypeBindingSample.Account> temp49;
            this.Manager.Comment("executing step \'call SearchAccounts(100F)\'");
            temp49 = TypeBindingSample.AccountImpl.SearchAccounts(((float)(100D)));
            this.Manager.Comment("reaching state \'S38\'");
            this.Manager.Comment("checking step \'return SearchAccounts/{}\'");
            TestManagerHelpers.AssertNotNull(this.Manager, temp49, "return of SearchAccounts, state S38");
            TestManagerHelpers.AssertAreEqual<Microsoft.Xrt.Runtime.RuntimeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>>(this.Manager, Microsoft.Xrt.Runtime.RuntimeSupport.MakeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>(), temp49.Rep, "return of SearchAccounts, state S38, field selection Rep");
            this.Manager.Comment("reaching state \'S45\'");
            Microsoft.Modeling.Set<TypeBindingSample.Account> temp50;
            this.Manager.Comment("executing step \'call SearchAccounts(20F)\'");
            temp50 = TypeBindingSample.AccountImpl.SearchAccounts(((float)(20D)));
            this.Manager.Comment("reaching state \'S52\'");
            this.Manager.Comment("checking step \'return SearchAccounts/{}\'");
            TestManagerHelpers.AssertNotNull(this.Manager, temp50, "return of SearchAccounts, state S52");
            TestManagerHelpers.AssertAreEqual<Microsoft.Xrt.Runtime.RuntimeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>>(this.Manager, Microsoft.Xrt.Runtime.RuntimeSupport.MakeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>(), temp50.Rep, "return of SearchAccounts, state S52, field selection Rep");
            this.Manager.Comment("reaching state \'S59\'");
            this.Manager.Comment("executing step \'call SetBalance(AccountDefinition#0,10F)\'");
            TypeBindingSample.AccountImpl.SetBalance(this.o.Value, ((float)(10D)));
            this.Manager.Comment("reaching state \'S66\'");
            this.Manager.Comment("checking step \'return SetBalance\'");
            this.Manager.Comment("reaching state \'S73\'");
            float temp51;
            this.Manager.Comment("executing step \'call GetBalance(AccountDefinition#0)\'");
            temp51 = TypeBindingSample.AccountImpl.GetBalance(this.o.Value);
            this.Manager.Comment("reaching state \'S80\'");
            this.Manager.Comment("checking step \'return GetBalance/10F\'");
            TestManagerHelpers.AssertAreEqual<float>(this.Manager, ((float)(10D)), temp51, "return of GetBalance, state S80");
            this.Manager.Comment("reaching state \'S86\'");
            Microsoft.Modeling.Set<TypeBindingSample.Account> temp52;
            this.Manager.Comment("executing step \'call SearchAccounts(100F)\'");
            temp52 = TypeBindingSample.AccountImpl.SearchAccounts(((float)(100D)));
            this.Manager.Comment("reaching state \'S92\'");
            this.Manager.Comment("checking step \'return SearchAccounts/{}\'");
            TestManagerHelpers.AssertNotNull(this.Manager, temp52, "return of SearchAccounts, state S92");
            TestManagerHelpers.AssertAreEqual<Microsoft.Xrt.Runtime.RuntimeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>>(this.Manager, Microsoft.Xrt.Runtime.RuntimeSupport.MakeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>(), temp52.Rep, "return of SearchAccounts, state S92, field selection Rep");
            this.Manager.Comment("reaching state \'S98\'");
            Microsoft.Modeling.Set<TypeBindingSample.Account> temp53;
            this.Manager.Comment("executing step \'call SearchAccounts(20F)\'");
            temp53 = TypeBindingSample.AccountImpl.SearchAccounts(((float)(20D)));
            this.Manager.Comment("reaching state \'S104\'");
            this.Manager.Comment("checking step \'return SearchAccounts/{}\'");
            TestManagerHelpers.AssertNotNull(this.Manager, temp53, "return of SearchAccounts, state S104");
            TestManagerHelpers.AssertAreEqual<Microsoft.Xrt.Runtime.RuntimeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>>(this.Manager, Microsoft.Xrt.Runtime.RuntimeSupport.MakeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>(), temp53.Rep, "return of SearchAccounts, state S104, field selection Rep");
            this.Manager.Comment("reaching state \'S110\'");
            this.Manager.Comment("executing step \'call SetBalance(AccountDefinition#0,100F)\'");
            TypeBindingSample.AccountImpl.SetBalance(this.o.Value, ((float)(100D)));
            this.Manager.Comment("reaching state \'S116\'");
            this.Manager.Comment("checking step \'return SetBalance\'");
            this.Manager.Comment("reaching state \'S122\'");
            float temp54;
            this.Manager.Comment("executing step \'call GetBalance(AccountDefinition#0)\'");
            temp54 = TypeBindingSample.AccountImpl.GetBalance(this.o.Value);
            this.Manager.Comment("reaching state \'S128\'");
            this.Manager.Comment("checking step \'return GetBalance/100F\'");
            TestManagerHelpers.AssertAreEqual<float>(this.Manager, ((float)(100D)), temp54, "return of GetBalance, state S128");
            this.Manager.Comment("reaching state \'S132\'");
            Microsoft.Modeling.Set<TypeBindingSample.Account> temp55;
            this.Manager.Comment("executing step \'call SearchAccounts(20F)\'");
            temp55 = TypeBindingSample.AccountImpl.SearchAccounts(((float)(20D)));
            this.Manager.Comment("reaching state \'S136\'");
            this.Manager.Comment("checking step \'return SearchAccounts/{}\'");
            TestManagerHelpers.AssertNotNull(this.Manager, temp55, "return of SearchAccounts, state S136");
            TestManagerHelpers.AssertAreEqual<Microsoft.Xrt.Runtime.RuntimeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>>(this.Manager, Microsoft.Xrt.Runtime.RuntimeSupport.MakeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>(), temp55.Rep, "return of SearchAccounts, state S136, field selection Rep");
            this.Manager.Comment("reaching state \'S140\'");
            Microsoft.Modeling.Set<TypeBindingSample.Account> temp56;
            this.Manager.Comment("executing step \'call SearchAccounts(100F)\'");
            temp56 = TypeBindingSample.AccountImpl.SearchAccounts(((float)(100D)));
            this.Manager.Comment("reaching state \'S144\'");
            this.Manager.Comment("checking step \'return SearchAccounts/{Account{AccountDefinition#0}}\'");
            TestManagerHelpers.AssertNotNull(this.Manager, temp56, "return of SearchAccounts, state S144");
            TestManagerHelpers.AssertAreEqual<Microsoft.Xrt.Runtime.RuntimeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>>(this.Manager, Microsoft.Xrt.Runtime.RuntimeSupport.UpdateMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>(Microsoft.Xrt.Runtime.RuntimeSupport.MakeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>(), this.o.Value, this.Make<Microsoft.Xrt.Runtime.RuntimeMapElement<Microsoft.Xrt.Runtime.Singleton>>(new string[] {
                                "Element"}, new object[] {
                                Microsoft.Xrt.Runtime.Singleton.Single})), temp56.Rep, "return of SearchAccounts, state S144, field selection Rep");
            this.Manager.Comment("reaching state \'S148\'");
            this.Manager.Comment("executing step \'call Clear()\'");
            TypeBindingSample.AccountImpl.Clear();
            this.Manager.Comment("reaching state \'S152\'");
            this.Manager.Comment("checking step \'return Clear\'");
            this.Manager.Comment("reaching state \'S156\'");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S8
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void TestSuiteS8() {
            this.Manager.BeginTest("TestSuiteS8");
            this.Manager.Comment("reaching state \'S8\'");
            TypeBindingSample.Account temp57;
            this.Manager.Comment("executing step \'call CreateAccount()\'");
            temp57 = TypeBindingSample.AccountImpl.CreateAccount();
            this.Manager.Comment("reaching state \'S9\'");
            this.Manager.Comment("checking step \'return CreateAccount/AccountDefinition#0\'");
            TestManagerHelpers.AssertBind<TypeBindingSample.Account>(this.Manager, this.o, temp57, "return of CreateAccount, state S9");
            this.Manager.Comment("reaching state \'S18\'");
            float temp58;
            this.Manager.Comment("executing step \'call GetBalance(AccountDefinition#0)\'");
            temp58 = TypeBindingSample.AccountImpl.GetBalance(this.o.Value);
            this.Manager.Comment("reaching state \'S25\'");
            this.Manager.Comment("checking step \'return GetBalance/0F\'");
            TestManagerHelpers.AssertAreEqual<float>(this.Manager, ((float)(0D)), temp58, "return of GetBalance, state S25");
            this.Manager.Comment("reaching state \'S32\'");
            Microsoft.Modeling.Set<TypeBindingSample.Account> temp59;
            this.Manager.Comment("executing step \'call SearchAccounts(100F)\'");
            temp59 = TypeBindingSample.AccountImpl.SearchAccounts(((float)(100D)));
            this.Manager.Comment("reaching state \'S39\'");
            this.Manager.Comment("checking step \'return SearchAccounts/{}\'");
            TestManagerHelpers.AssertNotNull(this.Manager, temp59, "return of SearchAccounts, state S39");
            TestManagerHelpers.AssertAreEqual<Microsoft.Xrt.Runtime.RuntimeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>>(this.Manager, Microsoft.Xrt.Runtime.RuntimeSupport.MakeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>(), temp59.Rep, "return of SearchAccounts, state S39, field selection Rep");
            this.Manager.Comment("reaching state \'S46\'");
            Microsoft.Modeling.Set<TypeBindingSample.Account> temp60;
            this.Manager.Comment("executing step \'call SearchAccounts(20F)\'");
            temp60 = TypeBindingSample.AccountImpl.SearchAccounts(((float)(20D)));
            this.Manager.Comment("reaching state \'S53\'");
            this.Manager.Comment("checking step \'return SearchAccounts/{}\'");
            TestManagerHelpers.AssertNotNull(this.Manager, temp60, "return of SearchAccounts, state S53");
            TestManagerHelpers.AssertAreEqual<Microsoft.Xrt.Runtime.RuntimeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>>(this.Manager, Microsoft.Xrt.Runtime.RuntimeSupport.MakeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>(), temp60.Rep, "return of SearchAccounts, state S53, field selection Rep");
            this.Manager.Comment("reaching state \'S60\'");
            this.Manager.Comment("executing step \'call SetBalance(AccountDefinition#0,10F)\'");
            TypeBindingSample.AccountImpl.SetBalance(this.o.Value, ((float)(10D)));
            this.Manager.Comment("reaching state \'S67\'");
            this.Manager.Comment("checking step \'return SetBalance\'");
            this.Manager.Comment("reaching state \'S74\'");
            float temp61;
            this.Manager.Comment("executing step \'call GetBalance(AccountDefinition#0)\'");
            temp61 = TypeBindingSample.AccountImpl.GetBalance(this.o.Value);
            this.Manager.Comment("reaching state \'S81\'");
            this.Manager.Comment("checking step \'return GetBalance/10F\'");
            TestManagerHelpers.AssertAreEqual<float>(this.Manager, ((float)(10D)), temp61, "return of GetBalance, state S81");
            this.Manager.Comment("reaching state \'S87\'");
            Microsoft.Modeling.Set<TypeBindingSample.Account> temp62;
            this.Manager.Comment("executing step \'call SearchAccounts(100F)\'");
            temp62 = TypeBindingSample.AccountImpl.SearchAccounts(((float)(100D)));
            this.Manager.Comment("reaching state \'S93\'");
            this.Manager.Comment("checking step \'return SearchAccounts/{}\'");
            TestManagerHelpers.AssertNotNull(this.Manager, temp62, "return of SearchAccounts, state S93");
            TestManagerHelpers.AssertAreEqual<Microsoft.Xrt.Runtime.RuntimeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>>(this.Manager, Microsoft.Xrt.Runtime.RuntimeSupport.MakeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>(), temp62.Rep, "return of SearchAccounts, state S93, field selection Rep");
            this.Manager.Comment("reaching state \'S99\'");
            Microsoft.Modeling.Set<TypeBindingSample.Account> temp63;
            this.Manager.Comment("executing step \'call SearchAccounts(20F)\'");
            temp63 = TypeBindingSample.AccountImpl.SearchAccounts(((float)(20D)));
            this.Manager.Comment("reaching state \'S105\'");
            this.Manager.Comment("checking step \'return SearchAccounts/{}\'");
            TestManagerHelpers.AssertNotNull(this.Manager, temp63, "return of SearchAccounts, state S105");
            TestManagerHelpers.AssertAreEqual<Microsoft.Xrt.Runtime.RuntimeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>>(this.Manager, Microsoft.Xrt.Runtime.RuntimeSupport.MakeMap<TypeBindingSample.Account, Microsoft.Xrt.Runtime.Singleton>(), temp63.Rep, "return of SearchAccounts, state S105, field selection Rep");
            this.Manager.Comment("reaching state \'S111\'");
            this.Manager.Comment("executing step \'call Clear()\'");
            TypeBindingSample.AccountImpl.Clear();
            this.Manager.Comment("reaching state \'S117\'");
            this.Manager.Comment("checking step \'return Clear\'");
            this.Manager.Comment("reaching state \'S123\'");
            this.Manager.EndTest();
        }
        #endregion
    }
}
