using System.Collections.Generic;
using Sek.Modeling;

namespace ATSvc.Model
{
    /// <summary>The job-description struct passed to AddJob (the classic sample's JobInfo).</summary>
    public sealed class JobInfo
    {
        public string Command { get; set; }
        public int Time { get; set; }
    }

    /// <summary>A scheduled job, identified structurally by command + time.</summary>
    public sealed class Job
    {
        public string Command { get; set; }
        public int Time { get; set; }
    }

    /// <summary>
    /// The AT Service job-scheduler model, ported to SEK. Jobs are created dynamically and
    /// held in model state; GetJobInfo/DeleteJob take a Job parameter whose domain is the
    /// set of reachable jobs. AddJob's parameters are generated by Z3 from the Cord `where`.
    /// </summary>
    public sealed class AtsvcModel : ModelProgram
    {
        /// <summary>Model-level bound on the number of jobs (settable via a Cord state slice
        /// `{. AtsvcModel.JobBound = n; .}:`). Defaults to 2.</summary>
        public static int JobBound = 2;

        public List<Job> Jobs { get; set; } = new List<Job>();

        [Rule("ATService.AddJob")]
        public bool AddJob(JobInfo info, out int jobId)
        {
            Require(Jobs.Count < JobBound, "bound the number of jobs");
            Jobs.Add(new Job { Command = info.Command, Time = info.Time });
            jobId = Jobs.Count;
            return true;
        }

        [Rule("ATService.GetJobInfo")]
        public void GetJobInfo(Job job)
        {
            // Observation only.
        }

        [Rule("ATService.DeleteJob")]
        public void DeleteJob(Job job)
        {
            Jobs.Remove(job);
        }

        [AcceptingCondition]
        public bool Accepting() => true;
    }
}
