using System.Collections.Generic;
using Sek.Modeling;

namespace ATSvc.Model
{
    /// <summary>A scheduled job. Identity is structural (command + time).</summary>
    public sealed class Job
    {
        public string Command { get; set; }
        public int Time { get; set; }
    }

    /// <summary>
    /// The AT Service job-scheduler model, ported to SEK. Jobs are created dynamically and
    /// held in model state; GetJobInfo/DeleteJob take a Job parameter whose domain is the
    /// set of reachable jobs. AddJob's parameters are generated by Z3 from the Cord `where`.
    /// </summary>
    public sealed class AtsvcModel : ModelProgram
    {
        public List<Job> Jobs { get; set; } = new List<Job>();

        [Rule("ATService.AddJob")]
        public void AddJob(string command, int time)
        {
            Require(Jobs.Count < 2, "bound the number of jobs");
            Jobs.Add(new Job { Command = command, Time = time });
        }

        [Rule("ATService.GetJobInfo")]
        public void GetJobInfo(Job job)
        {
            // Observation only.
        }

        [Rule("ATService.DeleteJob")]
        public void DeleteJob(Job job)
        {
            Jobs.Remove(job);
        }

        [AcceptingCondition]
        public bool Accepting() => true;
    }
}
